[jobs.m6502]
command = [
	"cargo",
	"check",
	"--lib",
	"--no-default-features",
	"--features",
	"m6502"
]

[jobs.m68k]
command = [
	"cargo",
	"+nightly",
	"check",
	"--lib",
        "--no-default-features",
	"--features",
	"m68k"
]

[jobs.armv4t]
command = [
	"cargo",
	"check",
	"--lib",
        "--no-default-features",
	"--features",
	"armv4t"
]

[jobs.mips_isa]
command = [
"cargo", "test", "--", "mips::isa", "--include-ignored", "--nocapture"
]

[jobs.sm83_isa]
command = [
"cargo", "test", "--", "sm83::isa", "--include-ignored", "--nocapture"
]

[jobs.z80_dasm]
command = [
    "cargo",
    "test",
    "--",
    "backends::z80::data::test::dasm",
    "--nocapture",
]
